setwd("C:/Users/LBS-Finance/Desktop/Exploratory Data Analysis/courseproject1")
dt<-read.table("household_power_consumption.txt",header=FALSE,skip=66637,nrows=2880,sep=";",stringsAsFactors=FALSE)
dtn<-read.table("household_power_consumption.txt",header=TRUE,nrows=1,sep=";")
dim(dt)
names(dt)<-names(dtn)
str(dt)
library(lubridate)
time<-paste(dt$Date,dt$Time,sep=" ")
time2<-dmy_hms(time)
plot(time2,dt$Sub_metering_1,type="n",ylab="Energy sub metering",xlab=" ")
lines(time2,dt$Sub_metering_1)
lines(time2,dt$Sub_metering_2,col="red")
lines(time2,dt$Sub_metering_3,col="blue")
legend("topright",legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),lty=1,
       col=c("black","red","blue"))
dev.copy(png,file="plot3.png")
dev.off()
